name: Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Replace variables in _config.fluid.yml
        run: |
          sed -i "s/APP_ID/${{ secrets.APP_ID }}/g" _config.fluid.yml
          sed -i "s/APP_KEY/${{ secrets.APP_KEY }}/g" _config.fluid.yml
          sed -i "s/APP_SERVER/${{ secrets.APP_SERVER }}/g" _config.fluid.yml
      - name: Use Node.js 21.6.1
        uses: actions/setup-node@main
        with:
          node-version: '21'
      - name: Cache NPM dependencies
        uses: actions/cache@main
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
